# Request
string command # move, pick, place, mount, unmount, check_mounted_tool
float32 speed
string position

micro_sp_emulation_msgs/Emulation emulated_response

---
# Response
bool success
string failure_cause
string info
string checked_mounted_tool